"""project timeline flag

Revision ID: 753db795f6b6
Revises: 963795626259
Create Date: 2026-09-22 23:36:19.094358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '753db795f6b6'
down_revision: Union[str, Sequence[str], None] = '963795626259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ``server_default`` first: projects that already exist keep the old behaviour
    # (frame names were parsed for sequence groups). New rows get the same default.
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('timeline', sa.Boolean(), nullable=False, server_default=sa.true())
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('timeline')

    # ### end Alembic commands ###
