"""The alembic migration must match the models and be reversible."""

from __future__ import annotations

from collections.abc import Iterator

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect, text

from v2.core.config import get_settings

REPO_ROOT = __import__("pathlib").Path(__file__).resolve().parents[2]

EXPECTED_TABLES = {
    "users",
    "sessions",
    "projects",
    "labels",
    "tasks",
    "annotations",
    "annotation_versions",
    "audit_log",
    "link_task_label",
    "link_task_user",
}


@pytest.fixture
def alembic_env(tmp_path, monkeypatch) -> Iterator[tuple[Config, str]]:
    url = f"sqlite+pysqlite:///{(tmp_path / 'v2_migrate.db').as_posix()}"
    monkeypatch.setenv("ZLSERVER_DATABASE_URL", url)
    get_settings.cache_clear()
    config = Config(str(REPO_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(REPO_ROOT / "v2" / "db" / "migrations"))
    try:
        yield config, url
    finally:
        get_settings.cache_clear()


def _tables(url: str) -> set[str]:
    engine = create_engine(url)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_upgrade_head_creates_every_table(alembic_env):
    config, url = alembic_env
    command.upgrade(config, "head")
    assert EXPECTED_TABLES <= _tables(url)


def test_migration_matches_models(alembic_env):
    """``alembic check`` fails when the models drifted from the migration."""
    config, url = alembic_env
    command.upgrade(config, "head")
    command.check(config)  # raises AutogenerateDiffsDetected on drift


def test_upgrade_from_the_initial_schema_with_existing_rows(alembic_env):
    """An existing deployment must survive the password/identity migrations.

    ``users.password_hash`` is NOT NULL, so a database that already has rows
    (OpenList-era accounts) must still upgrade; the identity-column rename then
    has to keep those rows' values.
    """
    config, url = alembic_env
    command.upgrade(config, "55f0e39f98e7")
    engine = create_engine(url)
    with engine.begin() as conn:
        conn.execute(
            text(
                "INSERT INTO users (oplist_user_id, name, email, role, active, finished_count, created_at)"
                " VALUES ('3', 'lyl', '', 'admin', 1, 0, '2026-01-01 00:00:00')"
            )
        )
    engine.dispose()

    command.upgrade(config, "head")

    engine = create_engine(url)
    with engine.begin() as conn:
        row = conn.execute(text("SELECT identity_id, name, role, password_hash FROM users")).one()
        session_columns = {c["name"] for c in inspect(engine).get_columns("sessions")}
    engine.dispose()
    assert (row.identity_id, row.name, row.role) == ("3", "lyl", "admin")
    assert row.password_hash == ""  # no password yet: an admin must set one
    assert "oplist_token" not in session_columns


def test_downgrade_base_is_clean(alembic_env):
    config, url = alembic_env
    command.upgrade(config, "head")
    command.downgrade(config, "base")
    assert _tables(url) == {"alembic_version"}
