"""The alembic migration must match the models and be reversible."""

from __future__ import annotations

from collections.abc import Iterator

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect

from v2.core.config import get_settings

REPO_ROOT = __import__("pathlib").Path(__file__).resolve().parents[2]

EXPECTED_TABLES = {
    "users",
    "sessions",
    "projects",
    "labels",
    "tasks",
    "annotations",
    "annotation_versions",
    "audit_log",
    "link_task_label",
    "link_task_user",
}


@pytest.fixture
def alembic_env(tmp_path, monkeypatch) -> Iterator[tuple[Config, str]]:
    url = f"sqlite+pysqlite:///{(tmp_path / 'v2_migrate.db').as_posix()}"
    monkeypatch.setenv("ZLV2_DATABASE_URL", url)
    get_settings.cache_clear()
    config = Config(str(REPO_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(REPO_ROOT / "v2" / "db" / "migrations"))
    try:
        yield config, url
    finally:
        get_settings.cache_clear()


def _tables(url: str) -> set[str]:
    engine = create_engine(url)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_upgrade_head_creates_every_table(alembic_env):
    config, url = alembic_env
    command.upgrade(config, "head")
    assert EXPECTED_TABLES <= _tables(url)


def test_migration_matches_models(alembic_env):
    """``alembic check`` fails when the models drifted from the migration."""
    config, url = alembic_env
    command.upgrade(config, "head")
    command.check(config)  # raises AutogenerateDiffsDetected on drift


def test_downgrade_base_is_clean(alembic_env):
    config, url = alembic_env
    command.upgrade(config, "head")
    command.downgrade(config, "base")
    assert _tables(url) == {"alembic_version"}
