"""user password hashes

Revision ID: 8394f2f1aff0
Revises: 55f0e39f98e7
Create Date: 2026-09-22 17:50:39.932142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8394f2f1aff0'
down_revision: Union[str, Sequence[str], None] = '55f0e39f98e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # `server_default=""` first: SQLite cannot add a NOT NULL column to a table
    # that already has rows without one (existing accounts simply have no
    # password until an admin sets one). The default is then dropped so the
    # column matches the model (a Python-side default).
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('password_hash', sa.String(length=255), nullable=False, server_default='')
        )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
